CREATE TABLESPACE tbs_livraria LOCATION '/home/gustavo/tablespace_livraria/livraria';
CREATE TABLESPACE tbs_indice LOCATION '/home/gustavo/tablespace_livraria/indice';
ALTER DATABASE postgres SET TABLESPACE tbs_livraria;
ALTER INDEX idx_cliente SET TABLESPACE tbs_indice;
ALTER INDEX idx_compra_cliente SET TABLESPACE tbs_indice;
ALTER INDEX idx_fkcompra_funcionario SET TABLESPACE tbs_indice;
ALTER INDEX idx_produtosComprados_compra SET TABLESPACE tbs_indice;
ALTER INDEX idx_produtosComprados_midia SET TABLESPACE tbs_indice;
ALTER INDEX idx_funcionario SET TABLESPACE tbs_indice;
ALTER INDEX idx_midia SET TABLESPACE tbs_indice;
ALTER INDEX idx_autor_midia SET TABLESPACE tbs_indice;
